import random

CHAMPION_QUOTES = [
    ("Aatrox", "I touched the stars, and saw the glorious light of a thousand suns! Now, blinded by this elegance, how could my purpose be anything... but dark..."),
    ("Aatrox", "How far I have fallen! A god… reduced to a prisoner!"),
    ("Aatrox", "I am not your enemy, I am the enemy!"),
    ("Ahri", "Should I make your pulse rise? Or stop completely?"),
    ("Ahri", "Are you sure you can handle me?"),
    ("Ahri", "They think they chase me. They have it backward."),
    ("Akali", "I'll make this quick."),
    ("Akali", "I make the rules. You just break them."),
    ("Akali", "I don't need a shadow to hide."),
    ("Akshan", "I am a Rogue Sentinel. 'Rogue' means I don't listen, 'Sentinel' means I look good doing it."),
    ("Akshan", "The scoundrel falls, the hero rises!"),
    ("Akshan", "Did I do that on purpose? Let's say yes."),
    ("Alistar", "You can't milk those!"),
    ("Alistar", "Grab life by the horns."),
    ("Alistar", "For the oppressed!"),
    ("Amumu", "I thought you'd never pick me."),
    ("Amumu", "Let's hug."),
    ("Amumu", "Is this... a game?"),
    ("Anivia", "The Freljord will awake."),
    ("Anivia", "This world is a fragile thing."),
    ("Anivia", "They cannot pierce the ice."),
    ("Annie", "Yay, Tibbers!"),
    ("Annie", "Have you seen my bear Tibbers?"),
    ("Annie", "You can't come to my tea party! 'Cause you're dead."),
    ("Aphelios", "So many weapons, Aphelios. The deadliest is your faith."),
    ("Aphelios", "I am with you. That is my promise, and my curse."),
    ("Aphelios", "Through my breath, you breathe. Through my agony, you strike."),
    ("Ashe", "All the world on one arrow."),
    ("Ashe", "A divided Freljord cannot survive. A united Freljord cannot fall."),
    ("Ashe", "Do not confuse mercy for weakness."),
    ("Aurelion Sol", "The stars look very different today."),
    ("Aurelion Sol", "I made the stars to illuminate the perpetual nothing, and mortals use them for 'relationship advice."),
    ("Aurelion Sol", "Cower, worship, beg. They're all valid reactions."),
    ("Aurora", "I'm something of a witch myself, you know!"),
    ("Aurora", "Knowledge is power... Try reading a book"),
    ("Aurora", "Spirits are so lucky they're not people."),
    ("Azir", "Shurima! Your emperor has returned!"),
    ("Azir", "Men die, but Shurima lives forever."),
    ("Azir", "You need not follow me... but you cannot stop me."),
    ("Bard", "𓌺𓂜𓏏𓆄𓆗"),
    ("Bard", "𓎛𓂓𓏛𓁐𓏪𓁹𓂋𓎛𓋴𓇋𓇋𓏏𓀁"),
    ("Bard", "𓂻𓅓𓈐𓈐𓈐𓇯"),
    ("Bel'Veth", "We are bound by destiny, Daughter of the Void. Help me, or watch your world burn."),
    ("Bel'Veth", "Behold your ending!"),
    ("Bel'Veth", "You fight for a future you will never see."),
    ("Blitzcrank", "Fired up and ready to serve."),
    ("Blitzcrank", "The time of man has come to an end."),
    ("Blitzcrank", "Ha. Ha. Ha. Ha."),
    ("Brand", "Ready to set the world on fire?!"),
    ("Brand", "This body is just a vessel."),
    ("Brand", "I am the fire that cleanses the world."),
    ("Braum", "The heart is the strongest muscle."),
    ("Braum", "You are safe with Braum"),
    ("Braum", "The heart is the strongest muscle."),
    ("Briar", "Eat your meat and vegetables, and you will grow big and strong like Braum!"),
    ("Caitlyn", "Boom. Headshot."),
    ("Caitlyn", "The law bends for no one."),
    ("Caitlyn", "Me, miss? Not by a long shot"),
    ("Camille", "Precision is the difference between a butcher and a surgeon."),
    ("Camille", "I'm the one who keeps the wolves at bay."),
    ("Camille", "Only cowards run!"),
    ("Cassiopeia", "Don't you find me... beautiful?"),
    ("Cassiopeia", "You think I'm a monster? You should see my sister."),
    ("Cassiopeia", "Look into my eyes... and see your end."),
    ("Cho'Gath", "Who will be eaten first?"),
    ("Cho'Gath", "No! I do not live under a bed! Fool!"),
    ("Cho'Gath", "Would you like some cheese with your wine?"),
    ("Corki", "I'm on it, black shoe!"),
    ("Corki", "This is major tom to ground control!"),
    ("Corki", "Consider yourself spanked, nugget!"),
    ("Darius", "I do not build walls. I tear them down!"),
    ("Darius", "They will regret opposing Noxus."),
    ("Darius", "Bled dry."),
    ("Diana", "A new moon is rising."),
    ("Diana", "The sun does not reveal the truth."),
    ("Diana", "The night is my shield."),
    ("Dr. Mundo", "Mundo goes where he pleases!"),
    ("Dr. Mundo", "Medical school... Yes, Mundo probably went there."),
    ("Dr. Mundo", "Uh... anyone see Mundo's brain scissors?"),
    ("Draven", "Welcome to the League of Draven!"),
    ("Draven", "Man, I am good."),
    ("Draven", "Let's admire me for a bit."),
    ("Ekko", "It's not about how much time you have, but how you use it."),
    ("Ekko", "You used to be cool."),
    ("Ekko", "I'd rather make mistakes than make nothing at all."),
    ("Elise", "Only the spider is safe in her web"),
    ("Elise", "Weak-willed fools!"),
    ("Elise", "The spider, I. And you, the fly."),
    ("Evelynn", "It's better when they scream."),
    ("Evelynn", "I love a man who knows what he wants."),
    ("Evelynn", "Let's see what you look like on the inside."),
    ("Ezreal", "You belong in a museum!"),
    ("Ezreal", "Who needs a map?!"),
    ("Ezreal", "Lot of good mages out there! None of them are this hot!"),
    ("Fiddlesticks", "Clowns are great for parties, they said... But now everyone's missing..."),
    ("Fiddlesticks", "Happy birthday to you... you belong in a zoo..."),
    ("Fiddlesticks", "Surprise!"),
    ("Fiora", "I long for a worthy opponent."),
    ("Fiora", "Others try. I succeed."),
    ("Fiora", "Sharp blade, sharp mind."),
    ("Fizz", "Let me at 'em!"),
    ("Fizz", "Shark"),
    ("Fizz", "Swimmingly!"),
    ("Galio", "GALIO IS HERE!"),
    ("Galio", "Justice takes flight!"),
    ("Galio", "Time to make a smash!"),
    ("Gangplank", "They can pay in gold... or blood."),
    ("Gangplank", "Dead men tell my tale."),
    ("Gangplank", "What shall we do with a drunken sailor?"),
    ("Garen", "DEMACIA!"),
    ("Garen", "I will not falter!"),
    ("Garen", "JUSTICE!"),
    ("Gnar", "Demaglio!"),
    ("Gnar", "Shugi shugi shugi!"),
    ("Gnar", "Gnar gada!"),
    ("Gragas", "The only time I have a drinking problem is when I spill it!"),
    ("Gragas", "I'll drink you under the table, scrub!"),
    ("Gragas", "If you're buying, I'm in!"),
    ("Graves", "Dead man walkin'."),
    ("Graves", "Feelin' lucky?"),
    ("Graves", "I ain't got time to bleed."),
    ("Gwen", "I used to be a doll... but look at me now!"),
    ("Gwen", "Snip, snip!"),
    ("Gwen", "I will stitch this broken world back together."),
    ("Hecarim", "BEHOLD THE MIGHT OF THE SHADOW ISLES!"),
    ("Hecarim", "RUN THEM DOWN!"),
    ("Hecarim", "NO MERCY!"),
    ("Heimerdinger", "For great science!"),
    ("Heimerdinger", "Eureka!"),
    ("Heimerdinger", "Indeed, a wise choice."),
    ("Hwei", "A painter meets their subject eye to eye."),
    ("Hwei", "A piece is never really finished, just abandoned."),
    ("Hwei", "What's heavy in the mind, becomes light on the page."),
    ("Illaoi", "Ah, everyone has a plan, until they get punched in the face."),
    ("Illaoi", "Struggle. Fight. Live!"),
    ("Illaoi", "LEARN, OR DROWN!"),
    ("Irelia", "Remember the Placidium!"),
    ("Irelia", "Ionians! Stand together!"),
    ("Irelia", "Fight for the First Lands!"),
    ("Ivern", "All life is precious... Yes, even yours, little bug."),
    ("Ivern", "Do you remember that one time we chased the clouds? That was a good day."),
    ("Ivern", "Looking sharp, old friend! Have you done something with your moss?"),
    ("Janna", "Yes, it's true. For only $2.95 a minute, I will leave you breathless."),
    ("Janna", "And you thought it was just a harmless breeze."),
    ("Janna", "Yes I know, I take your breath away."),
    ("Jarvan IV", "DEMACIA!!!"),
    ("Jarvan IV", "Today is a good day to die."),
    ("Jarvan IV", "Fetch the rest of your team; I'll wait."),
    ("Jax", "Bravest hero I ever knew was just a kid. Here's to you, champ."),
    ("Jax", "Who wants a piece of the champ?"),
    ("Jax", "Let's do this!"),
    ("Jayce", "To the skies!"),
    ("Jayce", "Face the future."),
    ("Jayce", "Hammer time!"),
    ("Jhin", "FOUR!"),
    ("Jhin", "Art requires a certain... cruelty."),
    ("Jhin", "In carnage, I bloom, like a flower in the dawn."),
    ("Jinx", "You think I'm crazy? You should see my sister!"),
    ("Jinx", "What's wrong with my pants???"),
    ("Jinx", "I accidentally did that on purpose."),
    ("K'Sante", "This is K'Sante, a champion with 4,700 HP, 329 Armor, and 201 MR, has Unstoppable, a Shield, and goes over walls. Has Airborne, and the cooldown is only 1 second too. It costs 15 Mana..."),
    ("K'Sante", "It seems I am built different."),
    ("K'Sante", "I WILL NOT YIELD!"),
    ("Kai'Sa", "I came for the hunt... but I'll stay for the fruit."),
    ("Kai'Sa", "You talk too much."),
    ("Kai'Sa", "When memories fade and darkness surrounds you… find the strength inside."),
    ("Kalista", "Death to all betrayers"),
    ("Kalista", "Trust... is a weapon."),
    ("Kalista", "There can be no justice. Only revenge."),
    ("Karma", "Lath Rian Oune Vi."),
    ("Karma", "Gaen Na Kyri Vi."),
    ("Karma", "Sae Eleisa Tera Vi."),
    ("Karthus", "Listen and rejoice in death!"),
    ("Karthus", "Sing with your final breath!"),
    ("Karthus", "I am the lightbringer!"),
    ("Kassadin", "I tried to silence my mother once. Boy, did I regret that."),
    ("Kassadin", "Silence!"),
    ("Kassadin", "The balance of power must be preserved"),
    ("Katarina", "Blood for Noxus!"),
    ("Katarina", "Why? Because I can."),
    ("Katarina", "If you run, you won't see me stab you!"),
    ("Kayle", "They shall tremble at my perfection."),
    ("Kayle", "Behold, the righteous flame!"),
    ("Kayle", "An eye for an eye."),
    ("Kayn", "Will you prove worthy? ...Probably not."),
    ("Kayn", "The child is gone. The killer remains."),
    ("Kayn", "So that's what dying feels like. Good thing I'm immortal!"),
    ("Kennen", "Yes, they make shurikens this small!"),
    ("Kennen", "The eyes never lie."),
    ("Kennen", "Balance in all things."),
    ("Kha'Zix", "Change is good."),
    ("Kha'Zix", "Consume and adapt."),
    ("Kha'Zix", "Fear the Void."),
    ("Kindred", "Never one... ...without the other."),
    ("Kindred", "Words are a shield, Wolf. Go bite them."),
    ("Kindred", "Those who run from us move faster toward us."),
    ("Kled", "CHAAAAAAAARGE!!!"),
    ("Kled", "Holy sh*t, where are we?!"),
    ("Kled", "I am Kled! High General of the First Legion Third Multiplication Double Admiral Artillery Vanguard Company! You will respect my authority!"),
    ("Kog'Maw", "Terror coming... daddy coming!"),
    ("Kog'Maw", "Feeding time!"),
    ("Kog'Maw", "Leave no scraps!"),
    ("LeBlanc", "The Black Rose shall bloom once more."),
    ("LeBlanc", "Patience, summoner."),
    ("LeBlanc", "Watch closely."),
    ("Lee Sin", "Master yourself, master the enemy."),
    ("Lee Sin", "Your will, my hands."),
    ("Lee Sin", "Force is meaningless without skill."),
    ("Leona", "The dawn has arrived"),
    ("Leona", "The sun always rises."),
    ("Leona", "Protect the fragile."),
    ("Lillia", "You can do this, Lillia. You are a strong, capable dream fawn. A-and you have a big stick. A-and you hit people with it but don't really mean it! Sorry."),
    ("Lillia", "I'm prancing. I'm singing. I'm prance-singing!"),
    ("Lillia", "How can I tip-toe, when I don't have toes?!"),
    ("Lissandra", "I will bury the world in ice."),
    ("Lissandra", "Close your eyes and let the cold take you."),
    ("Lissandra", "The cold will erase you."),
    ("Lucian", "Everybody dies. Some just need a little help"),
    ("Lucian", "For Senna!"),
    ("Lucian", "The shadows are rising! ...Wait, that's just my shadow. My bad."),
    ("Lulu", "That tasted purple!"),
    ("Lulu", "Just a pinch of pixie dust!"),
    ("Lulu", "Let's go trip over a rainbow!"),
    ("Lux", "With a positive attitude, anything is possible!"),
    ("Lux", "Demaciaa!"),
    ("Lux", "Stay positive!"),
    ("Malphite", "Rock solid."),
    ("Malphite", "You will lose"),
    ("Malphite", "Caught between a rock and a hard place."),
    ("Malzahar", "Oblivion awaits."),
    ("Malzahar", "We are timeless. We are legion."),
    ("Malzahar", "Do not struggle. Accept the inevitable"),
    ("Maokai", "I do nature's bidding... to the very end."),
    ("Maokai", "Flee into the forest? I am the forest."),
    ("Maokai", "The trees have learned violence."),
    ("Master Yi", "A true master is an eternal student."),
    ("Master Yi", "The key to immortality? Not dying."),
    ("Master Yi", "The focused mind can pierce stone."),
    ("Milio", "Ultra Mega Fire Kick!"),
    ("Milio", "We did it! Yeah!"),
    ("Milio", "Stop, drop, and roll!"),
    ("Miss Fortune", "Fortune doesn't favor fools."),
    ("Miss Fortune", "How do you like my guns... Shock, and Awe!"),
    ("Miss Fortune", "Sure you can handle me, summoner?"),
    ("Mordekaiser", "Destiny. Domination. Deceit."),
    ("Mordekaiser", "Iron stands eternal."),
    ("Mordekaiser", "All shall serve the true lord of the living and the dead."),
    ("Morgana", "They shall suffer as I have."),
    ("Morgana", "Feel my pain!"),
    ("Morgana", "Share my torment."),
    ("Naafiri", "There is no alpha, there is only the pack."),
    ("Naafiri", "One mind, spread among many vessels; this, is the way of the pack."),
    ("Naafiri", "It's not the strongest who survive—it's the most united."),
    ("Nami", "I decide what the tide will bring."),
    ("Nami", "Feet are strange."),
    ("Nami", "The ocean is a harsh mistress, but she has a great sense of humor."),
    ("Nasus", "The cycle of life and death continues. We will live, they will die."),
    ("Nasus", "Your legacy shall drift away, blown into eternity, like the sands of the desert."),
    ("Nasus", "Between life and death lies immortality."),
    ("Nautilus", "Beware the depths."),
    ("Nautilus", "You are in the deep end now!"),
    ("Nautilus", "Sometimes I think this anchor just weighs me down. ♪ Ba-da-dee, ba-da-do, ba-da-doo... ♪"),
    ("Neeko", "Neeko is not a sad tomato. She is a strong tomato!"),
    ("Neeko", "No more room for problems please. Only room for more cheesebreads."),
    ("Neeko", "Tricky tricky! You got the wrong Neeko!"),
    ("Nidalee", "They will fear the wild."),
    ("Nidalee", "The wild handles them easily."),
    ("Nidalee", "Instinct guides my steps."),
    ("Nilah", "I slay horrors, and I smile."),
    ("Nilah", "The river of fate drowns the unworthy."),
    ("Nilah", "Ashlesh's power is mine to command."),
    ("Nocturne", "DARKKKNESSSS..."),
    ("Nocturne", "Cut them from this world!"),
    ("Nocturne", "Do I scare you, summoner?"),
    ("Nunu", "Every adventure is better with a friend!"),
    ("Nunu", "Don't make the Yeti angry. You won't like him when he's angry!"),
    ("Nunu", "We'll be the greatest heroes ever!"),
    ("Olaf", "Leave nothing behind!"),
    ("Olaf", "To glory!"),
    ("Olaf", "This is the rhythm of destruction!"),
    ("Orianna", "We will slay them all. That will be fun."),
    ("Orianna", "The Ball is impatient."),
    ("Orianna", "I know what makes them tick. I know how to make the ticking stop."),
    ("Ornn", "The world is fine. People are the problem."),
    ("Ornn", "I have no followers. I do not want any. They get in the way."),
    ("Ornn", "I'm forging. Don't talk to me."),
    ("Pantheon", "In battle, we are reborn!"),
    ("Pantheon", "The heavens do not fear me because I am a god! They fear me because I am a man!"),
    ("Pantheon", "Stand up! Face me! We are what we overcome!"),
    ("Poppy", "I'm no hero. Just a yordle with a hammer."),
    ("Poppy", "Joke? I don't know any jokes."),
    ("Poppy", "Hammer, meet face!"),
    ("Pyke", "There's plenty of room at the bottom of the sea."),
    ("Pyke", "Did I kill you already? ...You look familiar."),
    ("Pyke", "I remember the captain's face... he looked like you."),
    ("Qiyana", "I am the shaper of lands, and who are you? A nobody."),
    ("Qiyana", "The rocks don't like you, the plants don't like you, and I'm pretty sure I don't like you."),
    ("Qiyana", "There are levels to this competition. Better stay on yours."),
    ("Quinn", "Justice takes wing."),
    ("Quinn", "I'd keep my head down if I were you."),
    ("Quinn", "Sometimes I swear that bird is just showing off."),
    ("Rakan", "You only have a spark of madness, you mustn't lose it."),
    ("Rakan", "I've been kicked around since I was born... I'm staying alive!"),
    ("Rakan", "When I get sad, I stop being sad and be awesome instead. True story!"),
    ("Rammus", "OK."),
    ("Rammus", "Hmm."),
    ("Rammus", "Mm-hmm"),
    ("Rek'Sai", "SCREEEEEEEEEEEEEEEEEEEEEEECH!!!!"),
    ("Rek'Sai", "SKRRRCH! KH-KH-KHAA!"),
    ("Rek'Sai", "k-k-k-k-thrrr... k-k-thrrr..."),
    ("Rell", "They wanted a weapon. Well, they got one."),
    ("Rell", "I don't need an army. I am an army."),
    ("Rell", "Let's see how much pressure your bones can take."),
    ("Renata Glasc", "Nothing's free. All I ask is your loyalty."),
    ("Renata Glasc", "Money can't buy happiness? Only someone born rich would agree with that."),
    ("Renata Glasc", "I provide people with two options: do what I want, or do what I want but with more steps."),
    ("Renekton", "As I live, all will die!"),
    ("Renekton", "Light meat, dark meat, it's all the same."),
    ("Renekton", "Embrace the jaws of death!"),
    ("Rengar", "A true hunter never rests."),
    ("Rengar", "There is the hunter and the hunted."),
    ("Rengar", "Prey on the weak and you will survive, prey on the strong and you will live."),
    ("Riven", "What is broken can be reforged."),
    ("Riven", "The time for talk is over."),
    ("Riven", "A broken blade is more than enough for the likes of you!"),
    ("Rumble", "Let's get in the fight!"),
    ("Rumble", "Who you calling little?!"),
    ("Rumble", "Ever looked up to a yordle?"),
    ("Ryze", "Ungeared from the world, I run."),
    ("Ryze", "If I had a rune for every mile I've run, I'd be done running."),
    ("Ryze", "None are worthy of my task... even me."),
    ("Samira", "You want style? You've found her."),
    ("Samira", "I'm the beauty and the beast."),
    ("Samira", "Showtime!"),
    ("Sejuani", "Trust nothing but your strength."),
    ("Sejuani", "I will not hide behind another shield."),
    ("Sejuani", "We win at any cost."),
    ("Senna", "If life is my curse, living is the cure."),
    ("Senna", "It's harder to hold a hand than hold a gun."),
    ("Senna", "No one fights alone in the Mist."),
    ("Seraphine", "Joy's too quiet without sorrow on the downbeat."),
    ("Seraphine", "Everyone fights to be heard. I'll fight to listen."),
    ("Seraphine", "I sing to help them find themselves. The stage just makes it easier."),
    ("Sett", "Everyone's got a plan, 'til they get slammed into the ground."),
    ("Sett", "A wise master once said, 'Be like water.' Guess I'm kind of a tsunami."),
    ("Sett", "When life gives you lemons, punch life in the throat."),
    ("Shaco", "For my next trick, I'll make you disappear!"),
    ("Shaco", "How about a magic trick?"),
    ("Shaco", "Why so serious?"),
    ("Shen", "If light travels so fast, how come it's never caught a ninja?"),
    ("Shen", "Target marked with honor."),
    ("Shen", "I walk the space between worlds."),
    ("Shyvana", "Blood is worth spilling for those worth protecting."),
    ("Shyvana", "Power means nothing if I abandon the powerless."),
    ("Shyvana", "Behold my true form! Tremble before the power of a dragon!"),
    ("Singed", "To shake, or not to shake."),
    ("Singed", "Shaken, not stirred."),
    ("Singed", "How about a drink?"),
    ("Sion", "COOOOOOWAAAAARDSSSSS!"),
    ("Sion", "NOTHING CAN STOP ME!"),
    ("Sion", "DIE!!!"),
    ("Sivir", "Loyalty isn't earned. It's bought."),
    ("Sivir", "Honor is the rust on a dull blade."),
    ("Sivir", "I always take my toll—blood or gold."),
    ("Skarner", "War is the weapon of the weak."),
    ("Skarner", "Your impact on this world is but a grain of sand in a vast desert! Let me show you."),
    ("Skarner", "I am Skarner of Clan Ọ̀pal-hin, progeny of broodmother Nixalẹ, and I will be your undoing."),
    ("Smolder", "Well, my mom's the biggest, baddest dragon around, and she's gonna burn you!"),
    ("Smolder", "Mom says I'm not supposed to eat you—but I'm too fast for her to stop me!"),
    ("Smolder", "Mom. Mom. Mooom! ...Hi!"),
    ("Sona", "Only you can hear me, Summoner. What masterpiece shall we play today?"),
    ("Sona", "Shall we resolve this dissonance?"),
    ("Sona", "A symphony of justice."),
    ("Soraka", "Yes, that was a banana. No one expects the banana."),
    ("Soraka", "No, I'm not happy to see you. Yes, that is a horn growing out of my head."),
    ("Soraka", "To heal and protect."),
    ("Swain", "Fear the power you do not see."),
    ("Swain", "Tell me again all the crimes I've committed, and I'll tell you the price of victory."),
    ("Swain", "To redraw the map, the blood of soldiers must be the ink."),
    ("Sylas", "No more cages!"),
    ("Sylas", "We are the true face of Demacia!"),
    ("Sylas", "When the rich steal from the poor, it's business. When the poor fight back, it's violence."),
    ("Syndra", "People fear what they cannot understand."),
    ("Syndra", "So much untapped power!"),
    ("Syndra", "I will not be restrained!"),
    ("Tahm Kench", "Call me king, call me demon. Water forgets the names of the drowned."),
    ("Tahm Kench", "Boy, the world's one river, and I'm its king. Ain't no place I ain't been; ain't no place I can't go again."),
    ("Tahm Kench", "An appetite for despair is easily satisfied."),
    ("Taliyah", "Keep your eyes on the horizon and your feet on the ground."),
    ("Taliyah", "Even the smallest stone can start an avalanche."),
    ("Taliyah", "You cannot be what you cannot envision."),
    ("Talon", "Live and die by the blade."),
    ("Talon", "Your allegiances mean nothing to me."),
    ("Talon", "Only fools pledge life to honor."),
    ("Taric", "Gems? Gems are truly outrageous. They are truly, truly, truly outrageous."),
    ("Taric", "Sparkle like a diamond."),
    ("Taric", "Demacia taught me how to stand. Targon taught me what to stand for."),
    ("Teemo", "Captain Teemo on duty!"),
    ("Teemo", "A part of you never leaves the jungle."),
    ("Teemo", "Armed and ready!"),
    ("Thresh", "Hook, line, and sinker."),
    ("Thresh", "Going somewhere?"),
    ("Thresh", "What delightful agony we shall inflict."),
    ("Tristana", "Once a Bandle gunner, always a Bandle gunner!"),
    ("Tristana", "Orders are more like guidelines, really."),
    ("Tristana", "Is that a rocket in your pocket?"),
    ("Trundle", "Time to troll!"),
    ("Trundle", "Defeat Trundle? Are you trolling?"),
    ("Trundle", "Don't hate the player, hate the club that's smashin' your face!"),
    ("Tryndamere", "This will be a slaughter!"),
    ("Tryndamere", "Aaaaaaargh!"),
    ("Tryndamere", "My right arm is a lot stronger than my left arm!"),
    ("Twisted Fate", "Lady Luck is smilin'."),
    ("Twisted Fate", "I'm one of a kind."),
    ("Twisted Fate", "Only a fool plays the hand he's dealt."),
    ("Twitch", "Oh, what's that smell? Oh, it's me!"),
    ("Twitch", "I WAS HIDING!"),
    ("Twitch", "SEWEEEEEEER SKEWER FOR EVERYBOOOOODY!"),
    ("Udyr", "Years of training, and the needs of others still ring louder than my own!"),
    ("Udyr", "Why, spirits? Why was I chosen? For this struggle, will there ever be rest?"),
    ("Udyr", "Mastery is a volcano, and I will rise within it like magma."),
    ("Urgot", "You cannot know strength... until you are broken."),
    ("Urgot", "I was not reborn in the depths, I merely refused to die."),
    ("Urgot", "Trapped in a pit of despair, I climbed out on the corpses."),
    ("Varus", "The guilty will know agony."),
    ("Varus", "The cost of your life is one arrow!"),
    ("Varus", "When you dance with death, lead."),
    ("Vayne", "Let us hunt those who have fallen to darkness."),
    ("Vayne", "The dark should fear me."),
    ("Vayne", "I smell black magics."),
    ("Veigar", "Know that if the tables were turned, I would show you no mercy!"),
    ("Veigar", "I will swallow your soul!"),
    ("Veigar", "All your base are belong to me!"),
    ("Vel'Koz", "Knowledge through... disintegration."),
    ("Vel'Koz", "Let's see what they're made of."),
    ("Vel'Koz", "Humans; simple, messy—yet, exceptional."),
    ("Vex", "Or whatever."),
    ("Vex", "Do the thing, Shadow."),
    ("Vex", "Comin' in sad!"),
    ("Vi", "Punch first. Ask questions while punching."),
    ("Vi", "If I want your opinion, I'll beat it out of you."),
    ("Vi", "I let my hands do the talking."),
    ("Viego", "Love ruins all."),
    ("Viego", "No price is too great. No atrocity beyond my reach. For her... I will do anything!"),
    ("Viego", "You are not the hero of this tale! You are not anything!"),
    ("Viktor", "Join the glorious evolution!"),
    ("Viktor", "Humanity can be so much more."),
    ("Viktor", "Machines are near perfect. I will make humanity even greater."),
    ("Vladimir", "Go ahead, be negative. You'll be just my type."),
    ("Vladimir", "I'm a universal recipient."),
    ("Vladimir", "The clot thickens."),
    ("Volibear", "I am the storm."),
    ("Volibear", "I am a god. I cannot die. But, do I live if I am not in the hearts of warriors?"),
    ("Volibear", "This place has been tamed. I will untame it!"),
    ("Warwick", "Blood runs... they all run."),
    ("Warwick", "It's only fun if they run."),
    ("Warwick", "The blood you spilled... brought me here."),
    ("Wukong", "I will be the best."),
    ("Wukong", "Every mistake is a lesson."),
    ("Wukong", "No matter how far it is to the top, it's still within my grasp!"),
    ("Xayah", "I can never resist an invitation to dance."),
    ("Xayah", "The next one to call me 'edgy' is getting choked to death."),
    ("Xayah", "Violence is my favorite form of negotiation."),
    ("Xerath", "I am eternal."),
    ("Xerath", "Lightning bolt! Lightning bolt! Lightning bolt!"),
    ("Xerath", "Power laning, power farming, power ganking, power kills! So many kills! Four-hundred kills!"),
    ("Xin Zhao", "One spear, one thousand battles."),
    ("Xin Zhao", "Here's a tip, and a spear behind it!"),
    ("Xin Zhao", "A thousand battles mean nothing, only the last one matters."),
    ("Yasuo", "Death is like the wind—always by my side."),
    ("Yasuo", "Honor is in the heart, not the name."),
    ("Yasuo", "A wanderer isn't always lost."),
    ("Yone", "One to cut, one to seal."),
    ("Yone", "Wear a mask long enough, and you forget the face beneath."),
    ("Yone", "Humans lie. Swords speak truth."),
    ("Yorick", "I am the rift between life and death. The thin divide between breath and grave."),
    ("Yorick", "Everyone I knew is dead. How are things with you?"),
    ("Yorick", "Remember my name. For one day, I will not."),
    ("Yuumi", "More of a dog person, huh?"),
    ("Yuumi", "Cats make great companions! Just ask my master... who disappeared under mysterious circumstances."),
    ("Yuumi", "Where's my fishy fishy fish for my dishy dishy dish?!"),
    ("Zac", "I may bend, but I don't break."),
    ("Zac", "I'm not as squishy as I look."),
    ("Zac", "It's not how much you can lift. It's how good you look!"),
    ("Zed", "The unseen blade is the deadliest."),
    ("Zed", "No technique is forbidden."),
    ("Zed", "Balance is a fool's master."),
    ("Zeri", "I belong here. We all belong here."),
    ("Zeri", "Stand up for your community, and it will stand up with you."),
    ("Zeri", "I stood up for my community. I can stand up for others, too."),
    ("Ziggs", "This'll be a blast!"),
    ("Ziggs", "Explosion first, questions later."),
    ("Ziggs", "I like my enemies like I like my bombs: about to explode!"),
    ("Zilean", "I knew you would do that."),
    ("Zilean", "Time flies like an arrow; fruit flies like a banana."),
    ("Zilean", "I have seen your death... it was painful."),
    ("Zoe", "Yes! This'll be fun! Right?"),
    ("Zoe", "Ooh, I like your spell! Can I have it? Thanks!"),
    ("Zoe", "Oops! Did that hurt? My bad!"),
    ("Zyra", "Feel the thorns' embrace."),
    ("Zyra", "Just a harmless flower."),
    ("Zyra", "Where are your friends? Mine are all around."),

]

def get_random_quote() -> tuple[str, str]:
    return random.choice(CHAMPION_QUOTES)