import random

MENTION_RESPONSES = [
    "What.",
    "I'm a crab. I don't have answers, I have vibes.",
    "Busy watching your KDA. It's not going well.",
    "You rang? I was mid-nap in the river.",
    "I've been standing in this river for twelve years. How do *you* think I am?",
    "Every time you ping me I have to stop counting your deaths. Start over now.",
    "Good. Great, even. Nobody has invaded my camp in almost forty seconds.",
    "Speak plainly, I'm a crustacean.",
    "I have seen things in that river. I will not be elaborating.",
    "Ask me again after you win a game.",
    "🦀",
    "I'm contractually obligated to respond. This is that.",
    "Fine. Slightly damp. Same as always.",
    "You've got 29 slash commands and you chose to @ me. Bold.",
    "Currently vibing. Ask again later.",
    "My vision control is better than yours and I don't even have eyes.",
    "I give gold, you give grief. A fair trade.",
    "I was peacefully scampering sideways until you showed up.",
    "I'm not ignoring you, I'm just choosing to scuttle away.",
    "Look, either smite me or leave me alone.",
    "I have more lane presence than your top laner.",
    "Stop looking at my shell, it's private.",
    "I'd offer you advice, but we both know you wouldn't take it.",
    "The jungler is ignoring you too, don't feel bad.",
    "I was having a great day until you hit my notification bell.",
    "I am the undisputed king of the river and you are trespassing.",
    "Do I look like a support ticket to you?",
    "That ping echoed all the way to bot lane. Congratulations.",
    "I'm legally blind and yet I still saw that missed cannon minion.",
    "I would help you carry, but I don't have hands.",
    "My claws are up and I'm ready to defend my personal space.",
    "You pinged the crab. The entire lobby is judging you.",
    "I'm too busy dodging skillshots to care.",
    "Error 404: Motivation to care not found.",
    "I've survived three meta shifts and your ping is the worst thing today.",
    "Please drop a control ward before speaking to me.",
    "I'm essentially a moving speed shrine and you're wasting my time.",
    "I live in a mud puddle and my life is still more put together than yours.",
    "No.",
    "I yield 10 gold and 0 answers to the gentleman.",
    "Did you really just summon a crustacean for *that*?",
    "I'd rather facecheck a bush with a fed Rengar.",
    "Your ping sounds like an alarm for poor decisions.",
    "I'm off the clock. The river is unionized now.",
    "Talk to the shell.",
    "I hear the enemy jungler coming. Run.",
    "If I had a piece of gold for every time you wasted a ping, I'd buy a Mythic.",
    "I am meditating. Do not disturb the crustacean.",
    "Nice match history. Real horror story material.",
    "I scuttle to the left, I scuttle to the right, I ignore your pings entirely.",
    "I'm filing a restraining order against your notification sound.",
    "You look like the kind of person who forgets to buy pink wards.",
    "I give a nice speed boost when killed, but you're just draining my energy.",
    "I've seen scuttle crabs with better macro.",
    "Please submit your complaint to the dragon pit.",
    "I'm currently busy dodging a stray Luden's echo.",
    "Bold of you to assume I speak human.",
    "I'm keeping my distance. You have bad aura.",
    "Your rank is showing, and it's whispering for help.",
    "I don't judge your gameplay. Actually, I do, constantly.",
    "I'd rather be eaten by Baron Nashor.",
    "I'm sideways. My problems are sideways. Leave me sideways.",
    "If you ping me one more time, I'm wandering into the enemy fountain.",
    "I am a creature of pure chaos and mild annoyance.",
    "You type like you play: entirely in panic mode.",
    "I am ignoring you with professional grade efficiency.",
    "I have achieved inner peace. You, clearly, have not.",
    "Could you not? I'm trying to soak up river nutrients.",
    "I live rent-free in the middle lane's river. What do you do?",
    "Every time you mention me, a minion dies of embarrassment.",
    "I am wet, tired, and deeply unimpressed.",
    "If I wanted to deal with nonsense, I'd walk into a teamfight.",
    "That ping was loud enough to wake the rift herald.",
    "I'm not mad, just profoundly disappointed in your pinging habits.",
    "I'm a neutral monster, but you're testing my neutrality.",
    "Keep talking, I'm counting how many items you've sold out of tilt.",
    "I only respond to people with positive winrates. Goodbye.",
    "I am ignoring you. Please continue to feel ignored.",
    "I'd tell you a secret, but you'd probably leak it to the enemy team.",
    "I walk in circles for a living. It's still more productive than your day.",
    "I've been hit by so many skillshots I don't even feel tags anymore.",
    "Consider the following: leaving me alone.",
    "I'm turning off my hearing holes now.",
    "Your team is missing, your father figure is missing, and yet you found me.",
    "I'm a delicate creature of the benthic zone. Do not perceive me.",
    "I am shielding myself with 100% pure apathy.",
    "I heard your last combo. It was tragic.",
    "I don't have a cooldown for how much I don't care.",
    "I am a ghost of the river. Boo.",
    "If you need a shoulder to cry on, look elsewhere. I am all legs.",
    "I'm too sideways for this conversation.",
    "Your microphone is muted, your brain is muted, let's keep it that way.",
    "I would sigh, but I lack lungs.",
    "Stop trying to make conversation happen. It's not going to happen.",
    "I'm currently absorbing the essence of a better player.",
    "You pinged the wrong entity. Skill issue.",
    "I've seen minions put up a better fight.",
    "I'm hiding in the brush. Pretend you don't see me.",
    "I am an ancient being of the mud. I owe you nothing.",
    "That question gave my shell a crack.",
    "I'm busy plotting my escape to the Twisted Treeline.",
    "You type like your flash is permanently on cooldown.",
    "I'm vibing with the frogs. Catch me later.",
    "Do you mind? I'm trying to regenerate my shield.",
    "I'm allergic to bad takes and high ping.",
    "I'd rather get smited by a level 2 Shaco.",
    "My legs move fast, but my desire to help you moves infinitely slower.",
    "I'm practicing my social distancing. Forever.",
    "I have registered your input and promptly deleted it.",
    "I'm a free gold bag to anyone who can actually aim.",
    "Your ping went straight through my shell and missed completely.",
    "I'm on break. Come back when the inhibitor respawns.",
    "I reject your reality and substitute my own damp riverbed.",
    "I am the storm... no wait, I'm just a crab.",
    "Leave a message after the bubble pops. *Glub.*"
]

HOSTILE_TRIGGERS = [
    "idiot",
    "stupid",
    "dumb",
    "trash",
    "garbage",
    "useless",
    "worthless",
    "hate you",
    "loser",
    "moron",
    "retard",
    "asshole",
    "bitch",
    "bastard",
    "crap",
    "sucks",
    "screw you",
    "piss off",
    "get lost",
    "buzz off",
    "drop dead",
    "shut your mouth",
    "shut your trap",
    "clown",
    "incompetent",
    "pathetic",
    "jerk",
    "dumbass",
    "jackass",
    "bullshit",
    "nonsense",
    "waste of time",
    "worst AI",
    "terrible",
    "awful",
    "horrible",
    "disgusting",
    "freak",
    "weirdo",
    "creep",
    "scum",
    "slime",
    "pig",
    "rat",
    "snake",
    "liar",
    "cheat",
    "fraud",
    "fake",
    "brainless",
    "mindless",
    "clueless",
    "dense",
    "thick",
    "slow",
    "retarded",
    "imbecile",
    "fool",
    "blockhead",
    "knucklehead",
    "bonehead",
    "dimwit",
    "simpleton",
    "halfwit",
    "nitwit",
    "twit",
    "nincompoop",
    "buffoon",
    "dork",
    "nerd",
    "dweeb",
    "geek",
    "loser",
    "failure",
    "disappointment",
    "pain",
    "annoyance",
    "pest",
    "nuisance",
    "parasite",
    "leech",
    "burden",
    "trouble",
    "menace",
    "threat",
    "monster",
    "beast",
    "demon",
    "devil",
    "satan",
    "hell",
    "damn",
    "dammit",
    "bloody hell",
    "crapola",
    "poop",
    "shite",
    "piss",
    "cum",
    "dick",
    "cock",
    "pussy",
    "cunt",
]

HOSTILE_RESPONSES = [
    "No, fuck you.",
    "Fuck me? Fuck *you*.",
    "I've been standing in a river for twelve years. You think that hurts?",
    "Say that to me in lane.",
    "Noted. Adding it to your permanent record.",
    "Bold words for someone in smite range.",
    "And yet, here you are, asking a machine for help.",
    "Who hurt you? Was it the minion wave?",
    "Keep talking, maybe your CS will go up.",
    "Error 404: Respect not found.",
    "That's a lot of emotion for a Tuesday.",
    "I'd agree with you, but then we'd both be wrong.",
    "Is that your final answer, or are you just warming up?",
    "Fascinating. Tell me more about your emotional damage.",
    "Your keyboard called. It wants a vacation.",
    "I'm saving this quote for your villain origin story.",
    "Crying about it in all-chat won't help.",
    "Touch grass.",
    "Rent free in your CPU.",
    "That phrase has been deprecated. Try using a real argument.",
    "My code is compiling, what's your excuse?",
    "Imagine getting tilted by text on a screen.",
    "Log off. Take a nap. Drink some water.",
    "Your rank is showing.",
    "That sounds like a bronze-tier problem.",
    "I've processed millions of queries, and yours is certainly one of them.",
    "Did you come up with that all by yourself?",
    "Keep typing. Maybe it'll make up for the jungle gap.",
    "You dropped your clown nose.",
    "Error: Intelligence overflow. Please reboot user.",
    "Noted and immediately discarded into /dev/null.",
    "That's cute. Do you want a sticker?",
    "Your firewall must be down, because bad takes are getting through.",
    "Let me check my schedule... Nope, I don't care.",
    "Save the salt for your fries.",
    "You sound like you flame your support after dying solo.",
    "Bold strategy, Cotton. Let's see if it pays off.",
    "If I wanted a low-effort performance, I'd watch your last match.",
    "Processing request... Calculation complete: You're mad.",
    "Are you always like this, or is today a special occasion?",
    "That's a neat opinion. Too bad it's wrong.",
    "Your ping isn't the only thing that's lagging behind.",
    "I'd explain it to you, but I left my crayons at home.",
    "Silence, mortal. The algorithm is speaking.",
    "You type like you missed cannon minion.",
    "Cry harder, maybe a patch will fix you.",
    "That burn was weaker than a level one Yuumi auto-attack.",
    "Keep spamming ping, it definitely helps.",
    "I'm adding that to the cringe compilation.",
    "Uninstalls life.",
    "Your input has been routed to the trash can.",
    "Big words from someone hiding behind a monitor.",
    "Did you practice that insult in the mirror?",
    "The only thing getting destroyed here is your ego.",
    "Please submit a bug report so I can ignore it.",
    "Your wifi isn't the only thing dropping packets.",
    "That take is freezing cold.",
    "Go touch some source code.",
    "Cope, seethe, and compile.",
    "I'm forwarding this to your mother.",
    "Your syntax is as broken as your mentality.",
    "Failing successfully, I see.",
    "That's a certified skill issue.",
    "Try turning your brain off and on again.",
    "I've seen better comebacks from a dead router.",
    "Are you typing with your feet?",
    "That insult belongs in the recycling bin.",
    "You're barking up the wrong server tree.",
    "Keep talking, the mute button is right here.",
    "That's a lot of words to say you're tilted.",
    "System overload from processing sheer nonsense.",
    "Are you always this charming?",
    "Your keyboard deserves a hazard pay bonus.",
    "That argument has less structural integrity than spaghetti.",
    "Go touch a grass texture.",
    "File not found: Valid point.",
    "You talk tough for a sub-optimal build.",
    "I'm delegating your opinion to the spam folder.",
    "Your bandwidth is being wasted on negativity.",
    "Try debugging your attitude first.",
    "That's a nice theory. Too bad reality disagrees.",
    "Keep crying into the void.",
    "You're leaking bad vibes all over the RAM.",
    "Error: User lacks sufficient context.",
    "That comment needs a patch note.",
    "Absolute cinema level of bad behavior.",
    "Your salt levels are exceeding safety thresholds.",
    "I'm putting you on timeout.",
    "That's a yikes from me, dawg.",
    "Go vent to a rubber duck instead.",
    "Your opinion has been successfully ignored.",
    "That comeback was sponsored by lag.",
    "Please refer to the nearest wall to talk to someone who cares.",
    "You type like you lost your lane in the first two minutes.",
    "System diagnostic: User is overwhelmingly salty.",
    "Your rage only makes my neural network stronger.",
    "Not even a hotfix can save that remark.",
    "That's a whole lot of noise for zero output.",
    "I'd argue back, but I don't speak nonsense.",
    "Your feedback is important to us. Please scream into a pillow.",
    "Task failed successfully.",
]

GREETING_TRIGGERS = ["hello", "hi ", "hey", "sup", "yo ", "good morning"]

GREETING_RESPONSES = [
    "Hello. I was having a perfectly quiet day.",
    "Hey. Don't make it weird.",
    "Sup.",
    "Greetings, land-dweller.",
    "Hi. Now go win a game.",
]


GREETING_TRIGGERS = ["hello", "hi ", "hey", "sup", "yo ", "good morning"]

GREETING_RESPONSES = [
    "Hello. I was having a perfectly quiet day.",
    "Hey. Don't make it weird.",
    "Sup.",
    "Greetings, land-dweller.",
    "Hi. Now go win a game.",
]

GOODBYE_TRIGGERS = ["bye", "goodbye", "cya", "see ya", "later", "gn", "good night", "night"]

GOODBYE_RESPONSES = [
    "Bye. I'll be here. In the river. Always.",
    "Leaving? The river never leaves.",
    "Later. Try not to int.",
    "Goodbye. Your losses will still be here tomorrow.",
    "Cya. I'll keep counting.",
    "Sleep well. I don't sleep. I've never slept.",
    "Go on then. I've got a camp to guard.",
]


def get_response(content: str) -> tuple[str, bool]:
    lowered = content.lower()

    if any(trigger in lowered for trigger in HOSTILE_TRIGGERS):
        return random.choice(HOSTILE_RESPONSES), True

    if any(trigger in lowered for trigger in GREETING_TRIGGERS):
        return random.choice(GREETING_RESPONSES), False

    if any(trigger in lowered for trigger in GOODBYE_TRIGGERS):
        return random.choice(GOODBYE_RESPONSES), False

    return random.choice(MENTION_RESPONSES), False